import { existsSync } from "node:fs";
import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import { expect } from "vitest";

import {
  requireLiveSuccess,
  test,
  throwWithCleanup,
} from "../../../../../../../tests/helpers/live.ts";

async function listRelativeSqlFiles(root: string, prefix = ""): Promise<ReadonlyArray<string>> {
  const entries = await readdir(join(root, prefix), { withFileTypes: true }).catch(() => []);
  const files: Array<string> = [];
  for (const entry of entries) {
    const relative = prefix.length === 0 ? entry.name : join(prefix, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listRelativeSqlFiles(root, relative)));
      continue;
    }
    if (entry.isFile() && entry.name.endsWith(".sql")) files.push(relative.split("\\").join("/"));
  }
  return files;
}

test("generates an editable declarative schema from a live database", async ({
  cli,
  project,
  workspace,
}) => {
  const suffix = `${Date.now()}${Math.floor(Math.random() * 10_000)
    .toString()
    .padStart(4, "0")}`;
  const table = `dogfood_note_${suffix}`;
  const enumType = `account_state_${suffix}`;
  const view = `auth_user_emails_${suffix}`;
  const appSchema = `dogfood_app_${suffix}`;
  const schemas = join(workspace.path, "supabase", "schemas");

  const query = (sql: string) => cli(["db", "query", "--db-url", project.dbUrl, sql]);

  let targetError: unknown;
  const cleanupErrors: Array<unknown> = [];
  try {
    const createType = await query(`create type public.${enumType} as enum ('pending', 'active')`);
    requireLiveSuccess(createType, "create enum setup");
    const createTable = await query(
      `create table public.${table} (
        id bigint generated by default as identity primary key,
        body text not null,
        loop_status text not null default 'draft'
      )`,
    );
    requireLiveSuccess(createTable, "create table setup");
    const createIndex = await query(
      `create index ${table}_loop_status_idx on public.${table} using btree (loop_status)`,
    );
    requireLiveSuccess(createIndex, "create index setup");
    const createView = await query(
      `create view public.${view} as select id, email from auth.users`,
    );
    requireLiveSuccess(createView, "create view setup");
    const createApp = await query(`create schema ${appSchema}`);
    requireLiveSuccess(createApp, "create custom schema setup");
    const createWidget = await query(
      `create table ${appSchema}.widget (
        id bigint generated by default as identity primary key,
        name text not null
      )`,
    );
    requireLiveSuccess(createWidget, "create custom table setup");
    const createFn = await query(
      `create function ${appSchema}.touch_widget() returns trigger language plpgsql as $$ begin return NEW; end; $$`,
    );
    requireLiveSuccess(createFn, "create trigger function setup");
    const createTrigger = await query(
      `create trigger widget_touch before update on ${appSchema}.widget for each row execute function ${appSchema}.touch_widget()`,
    );
    requireLiveSuccess(createTrigger, "create trigger setup");
    const enableRls = await query(`alter table ${appSchema}.widget enable row level security`);
    requireLiveSuccess(enableRls, "enable rls setup");
    const createPolicy = await query(
      `create policy widget_read on ${appSchema}.widget for select using (true)`,
    );
    requireLiveSuccess(createPolicy, "create policy setup");

    const result = await cli([
      "db",
      "schema",
      "declarative",
      "generate",
      "--db-url",
      project.dbUrl,
      "--overwrite",
      "--yes",
      "--experimental",
    ]);
    expect(result.exitCode, `${result.stdout}\n${result.stderr}`).toBe(0);
    expect(`${result.stdout}${result.stderr}`).toMatch(/Declarative schema written to/);

    const sqlFiles = await listRelativeSqlFiles(schemas);
    expect(sqlFiles).toEqual(
      expect.arrayContaining([
        `public/tables/${table}.sql`,
        `public/types/${enumType}.sql`,
        `public/views/${view}.sql`,
        `${appSchema}/schema.sql`,
        `${appSchema}/tables/widget.sql`,
        `${appSchema}/functions/touch_widget.sql`,
      ]),
    );
    expect(sqlFiles.some((file) => file.startsWith("auth/tables/"))).toBe(false);
    expect(sqlFiles.some((file) => file.startsWith("storage/"))).toBe(false);
    expect(sqlFiles.some((file) => file.startsWith("realtime/"))).toBe(false);
    expect(existsSync(join(schemas, ".pgdelta-export.json"))).toBe(true);

    const tableSql = await readFile(join(schemas, "public", "tables", `${table}.sql`), "utf8");
    expect(tableSql).toMatch(/GENERATED BY DEFAULT AS IDENTITY/i);
    expect(tableSql).toContain(table);
    expect(tableSql).toMatch(/CREATE INDEX/i);
    const enumSql = await readFile(join(schemas, "public", "types", `${enumType}.sql`), "utf8");
    expect(enumSql).toMatch(/ENUM/i);
    expect(enumSql).toContain("pending");
    const viewSql = await readFile(join(schemas, "public", "views", `${view}.sql`), "utf8");
    expect(viewSql).toContain("auth.users");
    const widgetSql = await readFile(join(schemas, appSchema, "tables", "widget.sql"), "utf8");
    expect(widgetSql).toMatch(/ENABLE ROW LEVEL SECURITY/i);
    expect(widgetSql).toMatch(/CREATE POLICY/i);
    expect(widgetSql).toMatch(/CREATE TRIGGER/i);

    const filtered = await cli([
      "db",
      "schema",
      "declarative",
      "generate",
      "--db-url",
      project.dbUrl,
      "--schema",
      "public",
      "--overwrite",
      "--yes",
      "--experimental",
    ]);
    expect(filtered.exitCode, `${filtered.stdout}\n${filtered.stderr}`).toBe(0);
    const filteredFiles = await listRelativeSqlFiles(schemas);
    expect(filteredFiles.some((file) => file.startsWith(`${appSchema}/`))).toBe(false);
    expect(filteredFiles).toEqual(
      expect.arrayContaining([
        `public/tables/${table}.sql`,
        `public/types/${enumType}.sql`,
        `public/views/${view}.sql`,
      ]),
    );
  } catch (error) {
    targetError = error;
  }

  for (const sql of [
    `drop schema if exists ${appSchema} cascade`,
    `drop view if exists public.${view}`,
    `drop table if exists public.${table}`,
    `drop type if exists public.${enumType}`,
  ]) {
    try {
      const dropped = await query(sql);
      requireLiveSuccess(dropped, `cleanup ${sql}`);
    } catch (error) {
      cleanupErrors.push(error);
    }
  }

  throwWithCleanup(targetError, cleanupErrors);
});
