import { existsSync } from "node:fs";
import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import { expect } from "vitest";

import {
  requireLiveSuccess,
  test,
  throwWithCleanup,
} from "../../../../../../../tests/helpers/live.ts";

async function listRelativeSqlFiles(root: string, prefix = ""): Promise<ReadonlyArray<string>> {
  const entries = await readdir(join(root, prefix), { withFileTypes: true }).catch(() => []);
  const files: Array<string> = [];
  for (const entry of entries) {
    const relative = prefix.length === 0 ? entry.name : join(prefix, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listRelativeSqlFiles(root, relative)));
      continue;
    }
    if (entry.isFile() && entry.name.endsWith(".sql")) files.push(relative.split("\\").join("/"));
  }
  return files;
}

test("generates an editable declarative schema from a live database", async ({
  cli,
  project,
  workspace,
}) => {
  const suffix = `${Date.now()}${Math.floor(Math.random() * 10_000)
    .toString()
    .padStart(4, "0")}`;
  const table = `dogfood_note_${suffix}`;
  const enumType = `account_state_${suffix}`;
  const view = `auth_user_emails_${suffix}`;
  const schemas = join(workspace.path, "supabase", "schemas");

  const query = (sql: string) => cli(["db", "query", "--db-url", project.dbUrl, sql]);

  let targetError: unknown;
  const cleanupErrors: Array<unknown> = [];
  try {
    const createType = await query(`create type public.${enumType} as enum ('pending', 'active')`);
    requireLiveSuccess(createType, "create enum setup");
    const createTable = await query(
      `create table public.${table} (
        id bigint generated by default as identity primary key,
        body text not null,
        state public.${enumType} not null default 'pending'
      )`,
    );
    requireLiveSuccess(createTable, "create table setup");
    const createView = await query(
      `create view public.${view} as select id, email from auth.users`,
    );
    requireLiveSuccess(createView, "create view setup");

    const result = await cli([
      "db",
      "schema",
      "declarative",
      "generate",
      "--db-url",
      project.dbUrl,
      "--overwrite",
      "--yes",
      "--experimental",
    ]);
    expect(result.exitCode, `${result.stdout}\n${result.stderr}`).toBe(0);
    expect(`${result.stdout}${result.stderr}`).toMatch(/Declarative schema written to/);

    const sqlFiles = await listRelativeSqlFiles(schemas);
    expect(sqlFiles).toEqual(
      expect.arrayContaining([
        `public/tables/${table}.sql`,
        `public/types/${enumType}.sql`,
        `public/views/${view}.sql`,
      ]),
    );
    expect(sqlFiles.some((file) => file.startsWith("auth/tables/"))).toBe(false);
    expect(sqlFiles.some((file) => file.startsWith("storage/"))).toBe(false);
    expect(sqlFiles.some((file) => file.startsWith("realtime/"))).toBe(false);
    expect(existsSync(join(schemas, ".pgdelta-export.json"))).toBe(true);

    const tableSql = await readFile(join(schemas, "public", "tables", `${table}.sql`), "utf8");
    expect(tableSql).toMatch(/GENERATED BY DEFAULT AS IDENTITY/i);
    expect(tableSql).toContain(table);
    const enumSql = await readFile(join(schemas, "public", "types", `${enumType}.sql`), "utf8");
    expect(enumSql).toMatch(/ENUM/i);
    expect(enumSql).toContain("pending");
    const viewSql = await readFile(join(schemas, "public", "views", `${view}.sql`), "utf8");
    expect(viewSql).toContain("auth.users");
  } catch (error) {
    targetError = error;
  }

  for (const sql of [
    `drop view if exists public.${view}`,
    `drop table if exists public.${table}`,
    `drop type if exists public.${enumType}`,
  ]) {
    try {
      const dropped = await query(sql);
      requireLiveSuccess(dropped, `cleanup ${sql}`);
    } catch (error) {
      cleanupErrors.push(error);
    }
  }

  throwWithCleanup(targetError, cleanupErrors);
});
